// Generated by CoffeeScript 2.3.2
(function() {
  var Property;

  Property = class Property {
    static property(name, accessors) {
      return Object.defineProperty(this.prototype, name, accessors);
    }

  };

  module.exports = Property;

}).call(this);
